"""
src/app.py
----------
Lightweight Web Interface for Animal Biological Class Predictor.
Built entirely with Python standard library (http.server) - zero extra dependencies.

Usage:
    python src/app.py
    Then open http://localhost:8000 in your browser.
"""

import os
import sys
import json
import joblib
import pandas as pd
from http.server import HTTPServer, BaseHTTPRequestHandler

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODELS_DIR = os.path.join(PROJECT_DIR, "models")
MODEL_PATH = os.path.join(MODELS_DIR, "decision_tree_model.joblib")
META_PATH = os.path.join(MODELS_DIR, "metadata.json")

FEATURE_COLUMNS = [
    "hair", "feathers", "eggs", "milk", "airborne", "aquatic",
    "predator", "toothed", "backbone", "breathes", "venomous",
    "fins", "legs", "tail", "domestic", "catsize"
]

# Load model and metadata at startup
if not os.path.exists(MODEL_PATH):
    raise FileNotFoundError("Trained model not found. Please run src/train.py first.")

MODEL = joblib.load(MODEL_PATH)
with open(META_PATH, "r", encoding="utf-8") as f:
    META = json.load(f)

HTML_PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Animal Biological Class Predictor</title>
    <style>
        :root {
            --primary: #1e3a8a;
            --primary-light: #3b82f6;
            --bg: #f8fafc;
            --card-bg: #ffffff;
            --text: #0f172a;
            --text-muted: #64748b;
            --border: #e2e8f0;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
        body { background: var(--bg); color: var(--text); padding: 24px 16px; display: flex; justify-content: center; }
        .container { max-width: 900px; width: 100%; background: var(--card-bg); border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.06); padding: 32px; border: 1px solid var(--border); }
        h1 { color: var(--primary); font-size: 1.8rem; margin-bottom: 8px; }
        .subtitle { color: var(--text-muted); margin-bottom: 24px; font-size: 0.95rem; }
        .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 16px; margin-bottom: 28px; }
        .field { background: #f1f5f9; padding: 12px 16px; border-radius: 8px; display: flex; justify-content: space-between; align-items: center; border: 1px solid #e2e8f0; }
        .field label { font-size: 0.9rem; font-weight: 500; }
        select { padding: 6px 10px; border-radius: 6px; border: 1px solid #cbd5e1; background: #fff; font-weight: 600; cursor: pointer; }
        .btn-predict { background: var(--primary); color: white; border: none; padding: 12px 28px; font-size: 1rem; font-weight: 600; border-radius: 8px; cursor: pointer; transition: background 0.2s; width: 100%; }
        .btn-predict:hover { background: var(--primary-light); }
        .result-box { margin-top: 28px; padding: 20px; border-radius: 8px; background: #f8fafc; border: 1px solid var(--border); display: none; }
        .result-title { font-size: 1.1rem; font-weight: 700; margin-bottom: 12px; }
        .badge { display: inline-block; padding: 6px 16px; background: #10b981; color: white; border-radius: 20px; font-weight: 700; font-size: 1.1rem; margin-bottom: 16px; }
        .prob-row { display: flex; align-items: center; margin-bottom: 8px; font-size: 0.9rem; }
        .prob-label { width: 100px; font-weight: 600; }
        .prob-bar-container { flex-grow: 1; height: 12px; background: #e2e8f0; border-radius: 6px; overflow: hidden; margin: 0 12px; }
        .prob-bar { height: 100%; background: var(--primary-light); border-radius: 6px; width: 0%; transition: width 0.4s ease; }
        .prob-pct { width: 50px; text-align: right; font-family: monospace; }
        .disclaimer { margin-top: 24px; padding: 12px; background: #fffbeb; border-left: 4px solid #f59e0b; border-radius: 4px; font-size: 0.85rem; color: #92400e; }
    </style>
</head>
<body>
<div class="container">
    <h1>🐾 Animal Biological Class Predictor</h1>
    <p class="subtitle">End-to-End Supervised ML Pipeline Demonstration (Decision Tree Classifier)</p>

    <div class="grid" id="form-grid">
        <!-- Fields generated by JS -->
    </div>

    <button class="btn-predict" onclick="makePrediction()">Predict Biological Class</button>

    <div class="result-box" id="result-box">
        <div class="result-title">Prediction Output:</div>
        <div>Predicted Class: <span class="badge" id="predicted-badge">Mammal</span></div>
        <div class="result-title" style="font-size:0.95rem; margin-top:12px;">Class Probabilities (Leaf Node Distribution):</div>
        <div id="prob-container"></div>
    </div>

    <div class="disclaimer">
        <strong>Educational Disclaimer:</strong> This model was trained on the public UCI Zoo dataset (N=83 for 5 vertebrate classes). It is designed to illustrate machine learning fundamentals, data splitting, parameter learning, and limitations. It is not intended for real-world zoological classification.
    </div>
</div>

<script>
const features = [
    { id: "hair", name: "Hair / Fur", type: "bool" },
    { id: "feathers", name: "Feathers", type: "bool" },
    { id: "eggs", name: "Lays Eggs", type: "bool" },
    { id: "milk", name: "Produces Milk", type: "bool" },
    { id: "airborne", name: "Can Fly", type: "bool" },
    { id: "aquatic", name: "Aquatic / Water", type: "bool" },
    { id: "predator", name: "Carnivorous Predator", type: "bool" },
    { id: "toothed", name: "Has Teeth", type: "bool" },
    { id: "backbone", name: "Has Backbone", type: "bool", default: "1" },
    { id: "breathes", name: "Breathes Air", type: "bool", default: "1" },
    { id: "venomous", name: "Venomous", type: "bool" },
    { id: "fins", name: "Has Fins", type: "bool" },
    { id: "legs", name: "Number of Legs", type: "num", options: [0, 2, 4, 6, 8], default: "4" },
    { id: "tail", name: "Has Tail", type: "bool", default: "1" },
    { id: "domestic", name: "Domesticated", type: "bool" },
    { id: "catsize", name: "Cat-sized or Larger", type: "bool" }
];

const grid = document.getElementById("form-grid");
features.forEach(f => {
    const div = document.createElement("div");
    div.className = "field";
    let optionsHtml = "";
    if (f.type === "bool") {
        const def = f.default || "0";
        optionsHtml = `<select id="${f.id}"><option value="0" ${def==="0"?"selected":""}>No (0)</option><option value="1" ${def==="1"?"selected":""}>Yes (1)</option></select>`;
    } else {
        const def = f.default || "4";
        optionsHtml = `<select id="${f.id}">${f.options.map(o => `<option value="${o}" ${def===o.toString()?"selected":""}>${o}</option>`).join("")}</select>`;
    }
    div.innerHTML = `<label for="${f.id}">${f.name}</label>${optionsHtml}`;
    grid.appendChild(div);
});

async function makePrediction() {
    const payload = {};
    features.forEach(f => {
        payload[f.id] = parseInt(document.getElementById(f.id).value);
    });

    try {
        const resp = await fetch("/predict", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload)
        });
        const data = await resp.json();

        document.getElementById("predicted-badge").innerText = data.predicted_class;
        const probContainer = document.getElementById("prob-container");
        probContainer.innerHTML = "";

        const sorted = Object.entries(data.probabilities).sort((a,b) => b[1] - a[1]);
        sorted.forEach(([cls, prob]) => {
            const pct = (prob * 100).toFixed(1) + "%";
            const row = document.createElement("div");
            row.className = "prob-row";
            row.innerHTML = `
                <span class="prob-label">${cls}</span>
                <div class="prob-bar-container"><div class="prob-bar" style="width: ${pct}"></div></div>
                <span class="prob-pct">${pct}</span>
            `;
            probContainer.appendChild(row);
        });

        document.getElementById("result-box").style.display = "block";
    } catch (err) {
        alert("Prediction error: " + err);
    }
}
</script>
</body>
</html>
"""

class SimpleMLHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/" or self.path == "/index.html":
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.end_headers()
            self.wfile.write(HTML_PAGE.encode("utf-8"))
        else:
            self.send_response(404)
            self.end_headers()

    def do_POST(self):
        if self.path == "/predict":
            content_length = int(self.headers.get("Content-Length", 0))
            post_body = self.rfile.read(content_length).decode("utf-8")
            features_dict = json.loads(post_body)

            # Ensure proper feature ordering
            vector = [features_dict.get(c, 0) for c in FEATURE_COLUMNS]
            df = pd.DataFrame([vector], columns=FEATURE_COLUMNS)

            pred_class = MODEL.predict(df)[0]
            probs = MODEL.predict_proba(df)[0]
            prob_dict = {cls: float(p) for cls, p in zip(MODEL.classes_, probs)}

            response_data = {
                "predicted_class": pred_class,
                "probabilities": prob_dict
            }

            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps(response_data).encode("utf-8"))
        else:
            self.send_response(404)
            self.end_headers()

    def log_message(self, format, *args):
        # Quiet standard HTTP request logs
        return

def main():
    port = 8000
    server_address = ("127.0.0.1", port)
    httpd = HTTPServer(server_address, SimpleMLHandler)
    print("=" * 65)
    print("   ANIMAL CLASSIFIER WEB APPLICATION (LIGHTWEIGHT SERVER)")
    print("=" * 65)
    print(f"[*] Serving web interface at: http://127.0.0.1:{port}/")
    print("[*] Press Ctrl+C to stop.")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\n[+] Server stopped.")

if __name__ == "__main__":
    main()
